-- ============================================
-- Movie Recommender (Pure SQL) — Schema (Oracle)
-- ============================================
-- Run this inside your Oracle XE user/schema
-- (e.g. via SQL Developer or SQL*Plus).
-- No CREATE DATABASE needed — Oracle uses schemas/users instead.

DROP TABLE ratings PURGE;
DROP TABLE movies PURGE;
DROP TABLE genres PURGE;
DROP TABLE users PURGE;

CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) UNIQUE
);

CREATE TABLE genres (
    genre_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name  VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE movies (
    movie_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR2(200) NOT NULL,
    genre_id      NUMBER,
    release_year  NUMBER(4),
    CONSTRAINT fk_movies_genre FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

CREATE TABLE ratings (
    rating_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    movie_id    NUMBER NOT NULL,
    rating      NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    rated_on    DATE,
    CONSTRAINT fk_ratings_user  FOREIGN KEY (user_id)  REFERENCES users(user_id),
    CONSTRAINT fk_ratings_movie FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
    CONSTRAINT uq_user_movie UNIQUE (user_id, movie_id)   -- one rating per user per movie
);
